version: "3.5"

services:
  consul:
    image: bitnami/consul:latest
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    # networks:
    #   - pplineer
    volumes:
      - /consul:/consul/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
